version: "3.7"

x-aliases:
  - &influx_db_name INFLUX_DB_NAME=***REMOVED***

services:
  influx:
    image: influxdb:1.8
    environment:
      - *influx_db_name
      - INFLUX_RP_DURATION=7d
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - INFLUXDB_SUBSCRIBER_ENABLED=false
      - INFLUXDB_CONTINUOUS_QUERIES_ENABLED=false
    volumes:
      - ./influx/start.sh:/docker-entrypoint-initdb.d/start.sh:ro
      - /data/influxdb:/var/lib/influxdb

  opcua-bridge:
    build: ./opcua-webhmi-bridge
    depends_on:
      - influx
    environment:
      - *influx_db_name
      - INFLUX_HOST=influx
      # Following environment variables will be obtained from `.env` file
      - OPC_SERVER_URL
      - OPC_MONITOR_NODE
      - OPC_RECORD_NODE

  web:
    depends_on:
      - opcua-bridge
