# Override file for production
version: "2.1"

services:
  influx:
    environment:
      - INFLUXDB_MONITOR_STORE_ENABLED=false

  web:
    build:
      context: ./web
      args:
        - NODE_TAG=12.18
        - GOLANG_TAG=1.15
    environment:
      - INFLUX_DB_NAME
      - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY

  reverse-proxy:
    labels:
      traefik.http.routers.influx-debug-noop.rule: "PathPrefix(`/influx/debug/`)"
      traefik.http.routers.influx-debug-noop.service: "noop@internal"
    ports:
      - "80:8000"
