# Override file for production
version: "3.7"

services:
  influx:
    environment:
      # Following environment variables will be obtained from `.env` file
      - INFLUX_DB_NAME

  opcua-bridge:
    environment:
      # Following environment variables will be obtained from `.env` file
      - INFLUX_DB_NAME
      - OPC_SERVER_URL
      - OPC_MONITOR_NODES
      - OPC_RECORD_NODES

  web:
    build:
      context: ./web
      args:
        # Following build arguments will be obtained from `.env` file
        - INFLUX_DB_NAME
    volumes:
      - caddy_data:/data

  reverse-proxy:
    command:
      - "--entryPoints.http.address=:8000"
      - "--log.level=WARN"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=tcp://dockerproxy:2375"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - "80:8000"

volumes:
  caddy_data:
