# Configuration common to development and production
version: "2.1"

services:
  centrifugo:
    image: centrifugo/centrifugo:v2.6
    command: centrifugo --config config.toml
    environment:
      # Following environment variables will be obtained from `.env` file
      - CENTRIFUGO_API_KEY
      - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY
      - CENTRIFUGO_PROXY_SUBSCRIBE_ENDPOINT=http://opcua-bridge:8008/centrifugo/subscribe
    expose:
      - "8000"
    labels:
      dozzle.enable: "true"
      traefik.enable: "true"
      traefik.http.middlewares.centrifugo-stripprefix.stripprefix.prefixes: "/centrifugo"
      traefik.http.middlewares.centrifugo-stripprefix.stripprefix.forceslash: "false"
      traefik.http.routers.centrifugo.middlewares: "centrifugo-stripprefix@docker"
      traefik.http.routers.centrifugo.rule: "PathPrefix(`/centrifugo/`)"
    networks:
      - net-private
    volumes:
      - ./centrifugo/config.toml:/centrifugo/config.toml:ro

  influx:
    image: influxdb:1.8
    environment:
      - INFLUX_RP_DURATION=7d
      - INFLUXDB_CONFIG_PATH=/etc/influxdb/influxdb.conf
      - INFLUXDB_MONITOR_STORE_ENABLED=false
      # Following environment variables will be obtained from `.env` file
      - INFLUX_DB_NAME
    labels:
      dozzle.enable: "true"
      traefik.enable: "true"
      traefik.http.middlewares.influx-stripprefix.stripprefix.prefixes: "/influx"
      traefik.http.middlewares.influx-stripprefix.stripprefix.forceslash: "false"
      traefik.http.routers.influx.middlewares: "influx-stripprefix@docker"
      traefik.http.routers.influx.rule: "PathPrefix(`/influx/`)"
    networks:
      - net-private
    volumes:
      - ./influxdb/config.toml:/etc/influxdb/influxdb.conf:ro
      - ./influxdb/start.sh:/docker-entrypoint-initdb.d/start.sh:ro
      - influxdb_data:/var/lib/influxdb

  log-viewer:
    image: amir20/dozzle:v2.2.0
    environment:
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
      - DOZZLE_BASE=/logs
      - DOZZLE_FILTER=label=dozzle.enable=true
    expose:
      - "8080"
    depends_on:
      - docker-socket-proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.logging.rule: "PathPrefix(`/logs/`) || Path(`/logs`)"
    networks:
      - net-private
    user: 2000:2000

  opcua-bridge:
    image: ghcr.io/cailloumajor/opcua-webhmi-bridge:20201214.1
    environment:
      - INFLUX_ROOT_URL=http://influx:8086
      - CENTRIFUGO_API_URL=http://centrifugo:8000/api
      # Following environment variables will be obtained from `.env` file
      - INFLUX_DB_NAME
      - CENTRIFUGO_API_KEY
      - OPC_SERVER_URL
      - OPC_MONITOR_NODES
      - OPC_RECORD_NODES
    labels:
      dozzle.enable: "true"
      traefik.enable: "true"
      traefik.http.middlewares.bridge-stripprefix.stripprefix.prefixes: "/bridge"
      traefik.http.middlewares.bridge-stripprefix.stripprefix.forceslash: "false"
      traefik.http.routers.opcua-bridge.middlewares: "bridge-stripprefix@docker"
      traefik.http.routers.opcua-bridge.rule: "PathPrefix(`/bridge/`)"
    networks:
      - net-private

  web:
    build:
      context: ./web
      args:
        - NODE_TAG=12.18
        - GOLANG_TAG=1.15
    environment:
      - INFLUX_DB_NAME
      - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY
    labels:
      dozzle.enable: "true"
      traefik.enable: "true"
      traefik.http.routers.web.rule: "PathPrefix(`/`)"
    networks:
      - net-private

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    environment:
      - CONTAINERS=1
    labels:
      dozzle.enable: "true"
    networks:
      - net-private
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  reverse-proxy:
    image: traefik:v2.2
    labels:
      dozzle.enable: "true"
    networks:
      - default
      - net-private
    ports:
      - "80:8000"
    user: 2000:2000
    volumes:
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro

networks:
  net-private:

volumes:
  influxdb_data:
