version: "2.3"

services:
  web:
    build:
      context: ./web/frontend/.devcontainer
      args:
        VARIANT: 16
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/workspace:cached

  reverse-proxy:
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.entryPoints: "traefik"
      traefik.http.routers.api.rule: "PathPrefix(`/api/`)"
      traefik.http.routers.api.service: "api@internal"
      traefik.http.routers.dashboard.entryPoints: "traefik"
      traefik.http.routers.dashboard.rule: "PathPrefix(`/`)"
      traefik.http.routers.dashboard.service: "dashboard@internal"
    ports:
      - "8080:8080"
