version: "2.1"

services:
  centrifugo:
    environment:
      - CENTRIFUGO_CLIENT_ANONYMOUS=true

  web:
    build:
      context: ./web/frontend/.devcontainer
      args:
        VARIANT: 12
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    expose:
      - "8080"
    user: node
    volumes:
      - .:/workspace:cached
    environment:
      - VUE_APP_INFLUX_DB_NAME=${INFLUX_DB_NAME}

  reverse-proxy:
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.entryPoints: "traefik"
      traefik.http.routers.api.rule: "PathPrefix(`/api/`)"
      traefik.http.routers.api.service: "api@internal"
      traefik.http.routers.dashboard.entryPoints: "traefik"
      traefik.http.routers.dashboard.rule: "PathPrefix(`/`)"
      traefik.http.routers.dashboard.service: "dashboard@internal"
    ports:
      - "8080:8000"
      - "8088:8080"
