version: "3.7"

services:
  influx:
    volumes:
      - influxdb:/var/lib/influxdb

  opcua_bridge:
    environment:
      - OPC_RECORD_INTERVAL

  web:
    build: ./web/.devcontainer
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace:cached
    tty: true

volumes:
  influxdb:
