# Configuration common to development and production
version: "2.1"

services:
  centrifugo:
    build:
      context: ./centrifugo
    command: --config /usr/local/etc/centrifugo.toml
    environment:
      - CENTRIFUGO_PROXY_SUBSCRIBE_ENDPOINT=http://opcua-bridge:8008/centrifugo/subscribe
      # Following environment variables will be obtained from `.env` file
      - CENTRIFUGO_API_KEY
      - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY
    labels:
      dozzle.enable: "true"
      traefik.enable: "true"
      traefik.http.middlewares.centrifugo-stripprefix.stripprefix.prefixes: "/centrifugo"
      traefik.http.middlewares.centrifugo-stripprefix.stripprefix.forceslash: "false"
      traefik.http.routers.centrifugo.middlewares: "centrifugo-stripprefix@docker"
      traefik.http.routers.centrifugo.rule: "PathPrefix(`/centrifugo/`)"
    networks:
      - net-private
    tty: true
    volumes:
      - ./centrifugo/config.toml:/usr/local/etc/centrifugo.toml:ro

  influxdb:
    image: influxdb:2.0.4
    environment:
      - INFLUXD_REPORTING_DISABLED=true
    healthcheck:
      test: influx ping || exit 1
    labels:
      dozzle.enable: "true"
      traefik.enable: "true"
      traefik.http.middlewares.influxdb-stripprefix.stripprefix.prefixes: "/influxdb"
      traefik.http.middlewares.influxdb-stripprefix.stripprefix.forceslash: "false"
      traefik.http.routers.influxdb.middlewares: "influxdb-stripprefix@docker"
      traefik.http.routers.influxdb.rule: "PathPrefix(`/influxdb/`)"
    networks:
      - net-private
    tty: true
    volumes:
      - influxdb_data:/var/lib/influxdb2

  log-viewer:
    image: amir20/dozzle:v3.6.3
    environment:
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
      - DOZZLE_BASE=/logs
      - DOZZLE_FILTER=label=dozzle.enable=true
    expose:
      - "8080"
    depends_on:
      - docker-socket-proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.logging.rule: "PathPrefix(`/logs/`) || Path(`/logs`)"
    networks:
      - net-private
    user: 2000:2000

  opcua-bridge:
    image: ghcr.io/cailloumajor/opcua-webhmi-bridge:20210406.1
    environment:
      - INFLUXDB_BASE_URL=http://influxdb:8086
      - CENTRIFUGO_API_URL=http://centrifugo:8000/api
      # Following environment variables will be obtained from `.env` file
      - INFLUXDB_ORG
      - INFLUXDB_BUCKET
      - INFLUXDB_WRITE_TOKEN
      - CENTRIFUGO_API_KEY
      - OPC_SERVER_URL
      - OPC_MONITOR_NODES
      - OPC_RECORD_NODES
    labels:
      dozzle.enable: "true"
      traefik.enable: "true"
      traefik.http.middlewares.bridge-stripprefix.stripprefix.prefixes: "/bridge"
      traefik.http.middlewares.bridge-stripprefix.stripprefix.forceslash: "false"
      traefik.http.routers.opcua-bridge.middlewares: "bridge-stripprefix@docker"
      traefik.http.routers.opcua-bridge.rule: "PathPrefix(`/bridge/`)"
    networks:
      - net-private
    volumes:
      - ./certificates/cert.der:/tmp/certs/cert.der:ro
      - ./certificates/key.pem:/tmp/certs/key.pem:ro

  web:
    build:
      context: ./web
    environment:
      - INFLUXDB_URL=/influxdb
      # Following environment variables will be obtained from `.env` file
      - INFLUXDB_ORG
      - INFLUXDB_BUCKET
      - INFLUXDB_READ_TOKEN
      - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY
    labels:
      dozzle.enable: "true"
      traefik.enable: "true"
      traefik.http.routers.web.rule: "Path(`/`, `/{file:[a-zA-Z0-9_.-]+}`)
        || PathPrefix(`/css/`, `/fonts/`, `/img/`, `/js/`, `/sockjs-node/`)"
    networks:
      - net-private

  docker-socket-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.1.1
    environment:
      - CONTAINERS=1
    labels:
      dozzle.enable: "true"
    networks:
      - net-private
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  reverse-proxy:
    image: traefik:v2.4.3
    labels:
      dozzle.enable: "true"
    networks:
      - default
      - net-private
    ports:
      - "80:8000"
    tty: true
    user: 2000:2000
    volumes:
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro

networks:
  net-private:

volumes:
  influxdb_data:
