# Configuration common to development and production
version: "3.7"

x-aliases:
  - &backend-network-name net-backend-${COMPOSE_PROJECT_NAME:-4nf3wt}

services:
  influx:
    image: influxdb:1.8
    environment:
      - INFLUX_RP_DURATION=7d
      - INFLUXDB_CONFIG_PATH=/etc/influxdb/influxdb.conf
    labels:
      dozzle.enable: "true"
      traefik.enable: "true"
      traefik.docker.network: *backend-network-name
      traefik.http.middlewares.influx-stripprefix.stripprefix.prefixes: "/influx"
      traefik.http.middlewares.influx-stripprefix.stripprefix.forceslash: "false"
      traefik.http.routers.influx.middlewares: "influx-stripprefix@docker"
      traefik.http.routers.influx.rule: "PathPrefix(`/influx/`)"
    networks:
      - net-backend
    volumes:
      - ./influxdb/config.toml:/etc/influxdb/influxdb.conf:ro
      - ./influxdb/start.sh:/docker-entrypoint-initdb.d/start.sh:ro
      - influxdb_data:/var/lib/influxdb

  log-viewer:
    image: amir20/dozzle:v2.2.0
    environment:
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
      - DOZZLE_BASE=/logs
      - DOZZLE_FILTER=label=dozzle.enable=true
    expose:
      - "8080"
    depends_on:
      - docker-socket-proxy
    labels:
      traefik.enable: "true"
      traefik.docker.network: *backend-network-name
      traefik.http.routers.logging.rule: "PathPrefix(`/logs/`) || Path(`/logs`)"
    networks:
      - net-backend
      - net-docker-socket
    user: 2000:2000

  opcua-bridge:
    build: ./opcua-webhmi-bridge
    environment:
      - INFLUX_HOST=influx
    labels:
      dozzle.enable: "true"
      traefik.enable: "true"
      traefik.docker.network: *backend-network-name
      traefik.http.middlewares.ws-stripprefix.stripprefix.prefixes: "/ws"
      traefik.http.middlewares.ws-stripprefix.stripprefix.forceslash: "false"
      traefik.http.routers.opcua-bridge.middlewares: "ws-stripprefix@docker"
      traefik.http.routers.opcua-bridge.rule: "PathPrefix(`/ws/`) || Path(`/ws`)"
    networks:
      - net-backend

  web:
    labels:
      dozzle.enable: "true"
      traefik.enable: "true"
      traefik.docker.network: *backend-network-name
      traefik.http.routers.web.rule: "PathPrefix(`/`)"
    networks:
      - net-backend

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    environment:
      - CONTAINERS=1
    labels:
      dozzle.enable: "true"
    networks:
      - net-docker-socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  reverse-proxy:
    image: traefik:v2.2
    labels:
      dozzle.enable: "true"
    networks:
      - net-backend
      - net-docker-socket
    user: 2000:2000
    volumes:
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro

networks:
  net-docker-socket:
  net-backend:
    name: *backend-network-name

volumes:
  influxdb_data:
