version: "3.7"

x-aliases:
  - &common-env-file ./.env.common

services:
  influx:
    env_file:
      - *common-env-file
    volumes:
      - influxdb:/var/lib/influxdb

  opcua-bridge:
    env_file:
      - *common-env-file
      - ./.env.opc

  web:
    env_file:
      - *common-env-file
    build: ./web/.devcontainer
    expose:
      - "8080"
    volumes:
      - .:/workspace:cached
    tty: true

  reverse-proxy:
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--entryPoints.http.address=:80"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - "8080:80"
      - "8088:8080"

volumes:
  influxdb:
