version: "3.7"

services:
  web:
    build: ./web/.devcontainer
    expose:
      - "8080"
    volumes:
      - .:/workspace:cached
    tty: true
    environment:
      # Following environment variables will be obtained from `.env` file
      - INFLUX_DB_NAME

  reverse-proxy:
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.entryPoints: "traefik"
      traefik.http.routers.api.rule: "PathPrefix(`/api/`)"
      traefik.http.routers.api.service: "api@internal"
      traefik.http.routers.dashboard.entryPoints: "traefik"
      traefik.http.routers.dashboard.rule: "PathPrefix(`/`)"
      traefik.http.routers.dashboard.service: "dashboard@internal"
    ports:
      - "8080:8000"
      - "8088:8080"
