[global]
checkNewVersion = false

[api]

[entryPoints.http]
address = ":8000"
[entryPoints.traefik]
address = ":8080"

[log]
level = "INFO"

[providers.docker]
endpoint = "tcp://docker-socket-proxy:2375"
exposedByDefault = false
