apiVersion: 1

datasources:
  - name: InfluxDB-Flux
    type: influxdb
    access: proxy
    url: ${INFLUXDB_URL}
    isDefault: true
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: true
      timeInterval: 1m
    secureJsonData:
      token: ${INFLUXDB_READ_TOKEN}
