[package]
name = "ui-config"
version = "0.1.0"
authors = ["Arnaud Rocher <arnaud.roche3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
