name: UI configuration service CI

on:
  push:
    branches:
      - main
    paths:
      - "ui-config/src/**"
      - "ui-config/Cargo.*"
      - "ui-config/Dockerfile"
      - ".github/workflows/ui-config.yml"
  pull_request:
    branches:
      - main
    paths:
      - "ui-config/src/**"
      - "ui-config/Cargo.*"
      - "ui-config/Dockerfile"
      - ".github/workflows/ui-config.yml"

defaults:
  run:
    working-directory: ui-config

jobs:
  quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-${{ github.job }}-cargo-${{ hashFiles('ui-config/Cargo.lock') }}
      - name: Get Rust version from Dockerfile
        id: get-rust-version
        run: echo "::set-output name=RUST_VERSION::$(grep -oP 'FROM rust:\K[\d.]+' Dockerfile)"
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ steps.get-rust-version.outputs.RUST_VERSION }}
          override: true
          components: rustfmt, clippy
      - name: Check code formatting
        run: cargo fmt --all -- --check
      - name: Check and lint
        run: cargo clippy -- -D warnings
  tests:
    name: Tests and code coverage
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Zinstrument-coverage
    steps:
      - uses: actions/checkout@v2
      - name: Setup Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-${{ github.job }}-cargo-${{ hashFiles('ui-config/Cargo.lock') }}
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: llvm-tools-preview
      - name: Install grcov
        run: cargo install grcov
      - name: Build the package
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: Generate coverage report
        run: grcov . -s . -b ./target/debug/ --branch --ignore-not-existing --ignore "/*" -o lcov.info
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/ui-config/lcov.info
          flag-name: ui-config-tests
          base-path: ui-config
